"""PowerPoint (.pptx) Deliverable Generator for Ramiel.

Phase 5: Deliverable Generation.
Generates structured PowerPoint presentations (.pptx) from agent summary content
using python-pptx.
"""

from __future__ import annotations

import uuid
from pathlib import Path
from typing import Any

from pptx import Presentation
from pptx.util import Pt


class PptxWriter:
    """Generates formatted Microsoft PowerPoint (.pptx) presentation decks."""

    def __init__(self, default_output_dir: str | Path = "data/uploads") -> None:
        self.output_dir = Path(default_output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate(
        self,
        content: dict[str, Any],
        filename: str | None = None,
    ) -> str:
        """Generate a PowerPoint presentation from structured slide content.

        Args:
            content: Structured dictionary containing:
                - 'title': Presentation title (str)
                - 'subtitle': Presentation subtitle (str)
                - 'slides': List of dicts with 'title' (str) and 'bullet_points' (list[str])
            filename: Custom filename (defaults to generated UUID filename)

        Returns:
            The filesystem path to the generated .pptx file.
        """
        prs = Presentation()

        # 1. Title Slide (Layout 0)
        title_slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(title_slide_layout)
        title = slide.shapes.title
        subtitle = slide.placeholders[1]

        title.text = content.get("title", "Executive Technical Briefing")
        subtitle.text = content.get(
            "subtitle", "Generated by Ramiel Sovereign Workbench"
        )

        # 2. Content Slides (Layout 1: Title and Content)
        bullet_slide_layout = prs.slide_layouts[1]
        slides_data = content.get("slides", [])

        for s_data in slides_data:
            s_title = s_data.get("title", "Overview")
            bullets = s_data.get("bullet_points", [])

            c_slide = prs.slides.add_slide(bullet_slide_layout)
            c_slide.shapes.title.text = s_title

            body_shape = c_slide.shapes.placeholders[1]
            tf = body_shape.text_frame
            tf.word_wrap = True

            for idx, bullet in enumerate(bullets):
                if idx == 0:
                    p = tf.paragraphs[0]
                else:
                    p = tf.add_paragraph()
                p.text = bullet
                p.font.size = Pt(14)
                p.level = 0

        # Save presentation
        out_filename = filename or f"presentation_{uuid.uuid4().hex[:6]}.pptx"
        out_path = self.output_dir / out_filename
        prs.save(str(out_path))
        return str(out_path)
