"""Integration tests for chat endpoint and admin routes (Phase 1)."""

from __future__ import annotations

from unittest.mock import AsyncMock, patch

import pytest
from httpx import ASGITransport, AsyncClient

from backend.main import app


class TestChatEndpoint:
    """Test /api/chat execution and trace recording."""

    @pytest.mark.anyio
    async def test_chat_offline_fallback(self) -> None:
        """When local model server is offline, endpoint returns guidance and records trace."""
        async with AsyncClient(
            transport=ASGITransport(app=app), base_url="http://test"
        ) as ac:
            res = await ac.post(
                "/api/chat",
                json={"message": "Hello sovereign agent", "session_id": "sess-test-1"},
            )
            assert res.status_code == 200
            data = res.json()
            assert "reply" in data
            assert data["session_id"] == "sess-test-1"
            assert data["model_used"] == "system-offline-fallback"
            assert data["task_id"].startswith("task-")

    @pytest.mark.anyio
    @patch("backend.api.routes_chat._vllm_client.check_health", new_callable=AsyncMock)
    @patch("backend.api.routes_chat._vllm_client.generate", new_callable=AsyncMock)
    async def test_chat_with_vllm(
        self, mock_generate: AsyncMock, mock_health: AsyncMock
    ) -> None:
        """When vLLM is online, endpoint dispatches prompt to vLLM."""
        mock_health.return_value = True
        mock_generate.return_value = "This is a response generated by Llama-3."

        async with AsyncClient(
            transport=ASGITransport(app=app), base_url="http://test"
        ) as ac:
            res = await ac.post(
                "/api/chat",
                json={"message": "Summarize steam turbine report"},
            )
            assert res.status_code == 200
            data = res.json()
            assert data["reply"] == "This is a response generated by Llama-3."
            assert data["model_used"] == "vllm:reasoning-primary"

    @pytest.mark.anyio
    async def test_admin_traces_endpoint(self) -> None:
        """Traces endpoint should return recorded chat events."""
        async with AsyncClient(
            transport=ASGITransport(app=app), base_url="http://test"
        ) as ac:
            # First perform a chat
            await ac.post(
                "/api/chat",
                json={"message": "Trace verification prompt"},
            )

            # Query admin traces
            res = await ac.get("/api/admin/traces")
            assert res.status_code == 200
            data = res.json()
            assert data["count"] > 0
            assert len(data["traces"]) > 0

    @pytest.mark.anyio
    async def test_admin_health_endpoint(self) -> None:
        """Admin health endpoint reports phase 1 and serving status."""
        async with AsyncClient(
            transport=ASGITransport(app=app), base_url="http://test"
        ) as ac:
            res = await ac.get("/api/admin/health")
            assert res.status_code == 200
            data = res.json()
            assert data["phase"] == "1"
            assert data["backend"] == "ok"
